<?PHP

/**
 * @file
 * Installation file for the purge module.
 */

/**
 * Implementation of hook_requirements().
 */
function purge_requirements($phase) {
  if ($phase !== 'runtime') {
    return [];
  }
  return \Drupal::service('purge.diagnostics')->getHookRequirementsArray();
}

/**
 * Implementation of hook_uninstall().
 */
function purge_uninstall() {
  if (\Drupal::database()->schema()->tableExists('purge_queue')) {
    \Drupal::database()->schema()->dropTable('purge_queue');
  }
}
